# Cyberpunk palette (matches ~/.config/kitty/current-theme.conf)
$rosewater = rgb(F7CCE7)
$rosewaterAlpha = F7CCE7

$flamingo = rgb(ED91CA)
$flamingoAlpha = ED91CA

$pink = rgb(E455AE)
$pinkAlpha = E455AE

$mauve = rgb(9370DB)
$mauveAlpha = 9370DB

$red = rgb(FB3048)
$redAlpha = FB3048

$maroon = rgb(710100)
$maroonAlpha = 710100

$peach = rgb(FF5048)
$peachAlpha = FF5048

$yellow = rgb(FDF500)
$yellowAlpha = FDF500

$green = rgb(28C775)
$greenAlpha = 28C775

$teal = rgb(1AC5B0)
$tealAlpha = 1AC5B0

$sky = rgb(5DF4FE)
$skyAlpha = 5DF4FE

$sapphire = rgb(3CDCD7)
$sapphireAlpha = 3CDCD7

$blue = rgb(AE94E4)
$blueAlpha = AE94E4

$lavender = rgb(CEBFEF)
$lavenderAlpha = CEBFEF

$text = rgb(E8FBFD)
$textAlpha = E8FBFD

$subtext1 = rgb(B8C7CA)
$subtext1Alpha = B8C7CA

$subtext0 = rgb(889298)
$subtext0Alpha = 889298

$overlay2 = rgb(7D7F84)
$overlay2Alpha = 7D7F84

$overlay1 = rgb(52545B)
$overlay1Alpha = 52545B

$overlay0 = rgb(272932)
$overlay0Alpha = 272932

$surface2 = rgb(331319)
$surface2Alpha = 331319

$surface1 = rgb(210E15)
$surface1Alpha = 210E15

$surface0 = rgb(14101F)
$surface0Alpha = 14101F

$base = rgb(040A10)
$baseAlpha = 040A10

$mantle = rgb(030710)
$mantleAlpha = 030710

$crust = rgb(020509)
$crustAlpha = 020509
