## name: Cyberpunk
## license: MIT
## blurb: Custom cyberpunk theme built from user-supplied palette (black0/red0-2/yellow0-1/green0/cyan0/blue0/purple0/pink0/magenta0/bg0-2/surface0).

#: The basic colors

foreground                      #E8FBFD
background                      #040A10
selection_foreground            none
selection_background            #331319


#: Cursor colors

cursor                          #E455AE
cursor_text_color               background


#: URL underline color when hovering with mouse

url_color                       #FDF500


#: kitty window border colors and terminal bell colors

active_border_color             #E455AE
inactive_border_color           #210E15
bell_border_color               #FB3048
visual_bell_color               none


#: Tab bar colors

active_tab_foreground           #040A10
active_tab_background           #E455AE
inactive_tab_foreground         #E455AE
inactive_tab_background         #331319
tab_bar_background              #040A10
tab_bar_margin_color            #040A10


#: The basic 16 colors

#: black
color0 #272932
color8 #7D7F84

#: red
color1  #FB3048
color9  #FF5048

#: green
color2  #28C775
color10 #5ED598

#: yellow
color3  #CFED58
color11 #FDF500

#: blue
color4  #9370DB
color12 #AE94E4

#: magenta
color5  #CB1DCD
color13 #E455AE

#: cyan
color6  #1AC5B0
color14 #5DF4FE

#: white
color7  #9BA7AC
color15 #E8FBFD
